In [185]:
employees = [
    {"emp_id": 101, "emp_name": "Rahul", "join_date": "2026-09-20", "salary": 75000.00},
    {"emp_id": 102, "emp_name": "Priya", "join_date": "2026-09-10", "salary": 65000.00},
    {"emp_id": 103, "emp_name": "Amit",  "join_date": "2026-08-25", "salary": 62000.00},
    {"emp_id": 104, "emp_name": "Sneha", "join_date": "2026-07-15", "salary": 69000.00},
    {"emp_id": 105, "emp_name": "Vikas", "join_date": "2026-09-01", "salary": 99000.00},
    {"emp_id": 106, "emp_name": "Rahul", "join_date": "2025-08-17", "salary": 78000.00},
    {"emp_id": 107, "emp_name": "hanu",  "join_date": "2024-11-24", "salary": 49000.00}
]

In [4]:
import pandas as pd
df=pd.DataFrame(employees)
df

   emp_id emp_name   join_date   salary
0     101    Rahul  2026-09-20  75000.0
1     102    Priya  2026-09-10  65000.0
2     103     Amit  2026-08-25  62000.0
3     104    Sneha  2026-07-15  69000.0
4     105    Vikas  2026-09-01  99000.0
5     106    Rahul  2025-08-17  78000.0
6     107     hanu  2024-11-24  49000.0

In [9]:
df['join_date']=pd.to_datetime(df.join_date)

In [19]:
df[df.join_date.dt.year == 2026]

   emp_id emp_name  join_date   salary
0     101    Rahul 2026-09-20  75000.0
1     102    Priya 2026-09-10  65000.0
2     103     Amit 2026-08-25  62000.0
3     104    Sneha 2026-07-15  69000.0
4     105    Vikas 2026-09-01  99000.0

In [29]:
[emp for emp in employees if emp['join_date'][:4]=='2026']

[{'emp_id': 101,
  'emp_name': 'Rahul',
  'join_date': '2026-09-20',
  'salary': 75000.0},
 {'emp_id': 102,
  'emp_name': 'Priya',
  'join_date': '2026-09-10',
  'salary': 65000.0},
 {'emp_id': 103,
  'emp_name': 'Amit',
  'join_date': '2026-08-25',
  'salary': 62000.0},
 {'emp_id': 104,
  'emp_name': 'Sneha',
  'join_date': '2026-07-15',
  'salary': 69000.0},
 {'emp_id': 105,
  'emp_name': 'Vikas',
  'join_date': '2026-09-01',
  'salary': 99000.0}]

In [ ]:
{emp['join_date'][:4] : emp['salary'] for emp in employees}

{'2026': 99000.0, '2025': 78000.0, '2024': 49000.0}

In [65]:
from collections import defaultdict
yearssumsalary=defaultdict(float)

for emp in employees:
    yearssumsalary[emp['join_date'][:4]]+=emp['salary']

In [66]:
yearssumsalary

defaultdict(float, {'2026': 370000.0, '2025': 78000.0, '2024': 49000.0})

In [68]:
yearly_salaries={}
for emp in employees:
    if emp['join_date'][:4] in yearly_salaries.keys():
        yearly_salaries[emp['join_date'][:4]]+=emp['salary']
    else:
        yearly_salaries[emp['join_date'][:4]]=emp['salary']

In [69]:
yearly_salaries

{'2026': 370000.0, '2025': 78000.0, '2024': 49000.0}

In [94]:
list(map(lambda x: x*x , range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [97]:
[emp for emp in employees if emp['salary']== max({emp['salary'] for emp in employees})]

[{'emp_id': 105,
  'emp_name': 'Vikas',
  'join_date': '2026-09-01',
  'salary': 99000.0}]

In [99]:
max(employees, key= lambda emp:emp['salary'])

{'emp_id': 105,
 'emp_name': 'Vikas',
 'join_date': '2026-09-01',
 'salary': 99000.0}

In [123]:
import numpy as np
max([1,2,3,4,5,5], key=[1,2,3,4,5,5].count)

5

In [125]:
min(employees, key= lambda emp:emp['join_date'])

{'emp_id': 107,
 'emp_name': 'hanu',
 'join_date': '2024-11-24',
 'salary': 49000.0}

In [181]:
dates=[]
for emp in employees:
    print(emp['join_date'])
    dates.append(emp['join_date'])
dates.sort()
sorted_list=[]
for date in dates:
    for emp in employees:
        if emp['join_date']==date:
            sorted_list.append(emp)
for i,emp in enumerate(sorted_list):
    if i>0:
        sorted_list[i]['cumulative_payroll']=+emp['salary']+sorted_list[i]['salary']
        print(emp['salary'], ' ', sorted_list[i]['salary'])
    else:
        sorted_list[i]['cumulative_payroll']+=emp['salary']

2026-09-20
2026-09-10
2026-08-25
2026-07-15
2026-09-01
2025-08-17
2024-11-24
78000.0   78000.0
69000.0   69000.0
62000.0   62000.0
99000.0   99000.0
65000.0   65000.0
75000.0   75000.0

In [190]:
employees.sort(key= lambda emp:emp['join_date'])
runningTotal=0.0

for emp in employees:
    runningTotal+=emp['salary']
    emp['cumulative_payroll']=runningTotal

In [191]:
employees

[{'emp_id': 107,
  'emp_name': 'hanu',
  'join_date': '2024-11-24',
  'salary': 49000.0,
  'cumulative_payroll': 49000.0},
 {'emp_id': 106,
  'emp_name': 'Rahul',
  'join_date': '2025-08-17',
  'salary': 78000.0,
  'cumulative_payroll': 127000.0},
 {'emp_id': 104,
  'emp_name': 'Sneha',
  'join_date': '2026-07-15',
  'salary': 69000.0,
  'cumulative_payroll': 196000.0},
 {'emp_id': 103,
  'emp_name': 'Amit',
  'join_date': '2026-08-25',
  'salary': 62000.0,
  'cumulative_payroll': 258000.0},
 {'emp_id': 105,
  'emp_name': 'Vikas',
  'join_date': '2026-09-01',
  'salary': 99000.0,
  'cumulative_payroll': 357000.0},
 {'emp_id': 102,
  'emp_name': 'Priya',
  'join_date': '2026-09-10',
  'salary': 65000.0,
  'cumulative_payroll': 422000.0},
 {'emp_id': 101,
  'emp_name': 'Rahul',
  'join_date': '2026-09-20',
  'salary': 75000.0,
  'cumulative_payroll': 497000.0}]

In [220]:
log_data = "ID:101-NAME:Rahul-DEPT:Eng;ID:102-NAME:Priya-DEPT:Data;ID:103-NAME:Amit-DEPT:Ops"
res=defaultdict()
for x in log_data.split(';'):
    print(x.split('-'))
    for item in x.split('-'):
        print(item.split(':'))
        # print(len(item))
        # print({item[i][0]:item[i][1] for i in range(len(item))})

['ID:101', 'NAME:Rahul', 'DEPT:Eng']
['ID', '101']
['NAME', 'Rahul']
['DEPT', 'Eng']
['ID:102', 'NAME:Priya', 'DEPT:Data']
['ID', '102']
['NAME', 'Priya']
['DEPT', 'Data']
['ID:103', 'NAME:Amit', 'DEPT:Ops']
['ID', '103']
['NAME', 'Amit']
['DEPT', 'Ops']

In [235]:
# Test your function with this:
nums = [10, 20, 30, 40, 50]
target = 70
# Expected Output: [2, 3] (because numbers[2] + numbers[3] -> 30 + 40 = 70)

def find_pair(nums, target):
    seen_number={}

    for current_index,current_number in enumerate(nums):
        complement = target-current_number

        if complement in seen_number:
            return seen_number[complement],current_index

        seen_number[current_number]=current_index

    return None

In [240]:
find_pair(nums=nums,target=30)

(0, 1)

In [225]:
sum(nums, lambda x:x+x==70)

TypeError: unsupported operand type(s) for +: 'function' and 'int'

In [234]:
sum_=0
for i in nums:
    sum_=sum_+i
    print(sum_)
    if sum_==60:
        print(i)

10
30
60
30
100
150

In [233]:
nums

[10, 20, 30, 40, 50]

In [351]:
a=[2,[3,4,6],[2,3],5,6]
sum_of_all=0
for i in a:
    if type(i) == list:
        sum_of_all+= sum(i)
    elif type(i)==int:
        sum_of_all=sum_of_all+i

print(sum_of_all)

31

In [341]:
nested_data = {
    "emp_id": 101,
    "profile": {
        "first_name": "Rahul",
        "last_name": "Sharma"
    },
    "finance": {
        "salary": 75000.00,
        "tax": {
            "bracket": "high",
            "percentage": 20
        }
    }
}

nested_data

{'emp_id': 101,
 'profile': {'first_name': 'Rahul', 'last_name': 'Sharma'},
 'finance': {'salary': 75000.0, 'tax': {'bracket': 'high', 'percentage': 20}}}

In [350]:
def flatten_dict(nested_dict, parent_key='', sep='_'):
    items = {}
    
    for k, v in nested_dict.items():
        # 1. Calculate the new combined key name
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        print(new_key)
        if isinstance(v,dict):
            items.update(flatten_dict(v,new_key,sep=sep))
        else:
            items[new_key]=v
    return items
flatten_dict(nested_dict=nested_data)

emp_id
profile
profile_first_name
profile_last_name
finance
finance_salary
finance_tax
finance_tax_bracket
finance_tax_percentage

{'emp_id': 101,
 'profile_first_name': 'Rahul',
 'profile_last_name': 'Sharma',
 'finance_salary': 75000.0,
 'finance_tax_bracket': 'high',
 'finance_tax_percentage': 20}

In [340]:
from collections import defaultdict

d_dict=defaultdict(dict)

raw_stream = [
    ("Eng", 4500.00, "Cloud Architecture"),
    ("Data", 3000.00, "LLM Training"),
    ("Eng", 1200.00, "CI/CD Pipeline"),
    ("Ops", 2500.00, "Security Audit"),
    ("Data", 1500.00, "LLM Training"), # Note duplicate project name here
]

# Write a loop to summarize this into a structured profile map
summary = {}

# Expected Output format:
# {
#    "Eng": {"total_spend": 5700.00, "projects": ["Cloud Architecture", "CI/CD Pipeline"]},
#    "Data": {"total_spend": 4500.00, "projects": ["LLM Training"]},  # Unique project tracking!
#    "Ops": {"total_spend": 2500.00, "projects": ["Security Audit"]}
# }

raw_stream

for dept,spend,project in raw_stream:
    if dept not in d_dict.keys():
        d_dict[dept]={'total_spend':0.0, 'projects':[]}
    d_dict[dept]['total_spend']+=float(spend)
    if project not in d_dict[dept]['projects']:
        d_dict[dept]['projects'].append(project)
dict(d_dict)

{'Eng': {'total_spend': 5700.0,
  'projects': ['Cloud Architecture', 'CI/CD Pipeline']},
 'Data': {'total_spend': 4500.0, 'projects': ['LLM Training']},
 'Ops': {'total_spend': 2500.0, 'projects': ['Security Audit']}}

In [329]:
d_dict

defaultdict(dict,
            {'Eng': {'total_spend': 4500.0,
              'projects': ['Cloud Architecture']},
             'Data': {'total_spend': 3000.0, 'projects': ['LLM Training']},
             'Ops': {'total_spend': 2500.0, 'projects': ['Security Audit']}})

In [305]:
def compress_status(signals: str) -> str:
    string_output=''
    count=0
    for ind,i in enumerate(signals):
        if signals[ind]==signals[ind-1]:
            count+=1
        else:
            string_output+=signals[ind-1]+str(count)
            count=1
    string_output+=signals[ind-1]+str(count)
    return string_output

# Execution Test
print(compress_status("AAAAABBBCCDAA"))
# Expected Output: "A5B3C2D1A2"

A5B3C2D1A2

In [381]:
inp_string="AAAAABBBCCDAA"
count=0
string_output=''
for ind,i in enumerate(inp_string):
    if inp_string[ind]==inp_string[ind-1]:
        count+=1
    else:
        string_output+=inp_string[ind-1]+str(count)
        count=1
string_output+=inp_string[ind]+str(count)
string_output

'A5B3C2D1A2'

In [365]:
string_output

'C1C1D2A2'

In [439]:
raw_logs = [
    {"device_id": "A1", "temperature": 23.5},
    {"device_id": None, "temperature": 15.0},          # Rule 1: Drop (Missing ID)
    {"device_id": "A2", "temperature": None},          # Rule 2: Replace with 20.0
    {"device_id": "A3", "temperature": 150.0},         # Rule 3: Drop (Outlier!)
    {"device_id": "   ", "temperature": 12.0},         # Rule 1: Drop (Empty string ID)
    {"device_id": "A4", "temperature": -12.5}          # Keep
]

def clean_sensor_data(logs):
    # Write your data cleaning logic loop here
    for idx,log in enumerate(logs):
        if log in logs and log['device_id']==None  or len(log['device_id'].strip())==0:
            logs.remove(log)
        if log in logs and log['temperature']==None:
            logs[idx]['temperature']=20.0
        if log in logs and abs(log['temperature'])>=100:
            logs.remove(log)
    return logs
    pass

clean_sensor_data(raw_logs)
# Expected Output:
# [
#   {"device_id": "A1", "temperature": 23.5},
#   {"device_id": "A2", "temperature": 20.0},
#   {"device_id": "A4", "temperature": -12.5}
# ]

[{'device_id': 'A1', 'temperature': 23.5},
 {'device_id': 'A2', 'temperature': None},
 {'device_id': '   ', 'temperature': 12.0},
 {'device_id': 'A4', 'temperature': -12.5}]

In [402]:
{'device_id': None}

{'device_id': None}

In [428]:
raw_logs[1]['temperature']=20

In [429]:
raw_logs

[{'device_id': None, 'temperature': 15.0},
 {'device_id': 'A2', 'temperature': 20},
 {'device_id': 'A3', 'temperature': 150.0},
 {'device_id': '   ', 'temperature': 12.0},
 {'device_id': 'A4', 'temperature': -12.5}]